name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          config-file: 'ArcGIS/standard-dependency-review-configuration/dependency-review-config.yml@v1'
          external-repo-token: ${{ secrets.SSP_DEPENDENCY_REVIEW_ACCESS_TOKEN }}
