name: khronicle

on:
  push:
    branches:
    - 'main'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
      - name: Publish (Maven)
        #if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        run: |
            echo -n "${{ secrets.MAVEN_SIGNING_KEY }}" | base64 --decode | gpg --import
            ./gradlew -PcentralUsername=${{ secrets.CENTRAL_USERNAME }} -PcentralPassword=${{ secrets.CENTRAL_PASSWORD }} publish
            ./gradlew -PcentralUsername=${{ secrets.CENTRAL_USERNAME }} -PcentralPassword=${{ secrets.CENTRAL_PASSWORD }} jreleaserDeploy

  xmllint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install tools
        run: sudo apt-get install -y libxml2-utils
      - name: Validate xml config
        run: xmllint --schema ./xml/logback.xsd.xml ./src/test/resources/assets/logger-config.xml
